package references

var PseudoInstructions = map[string]string{
	"DB":      "Pseudoinstruccion",
	"DW":      "Pseudoinstruccion",
	"DD":      "Pseudoinstruccion",
	"DQ":      "Pseudoinstruccion",
	"DT":      "Pseudoinstruccion",
	"SEGMENT": "Pseudoinstruccion",
	"ENDS":    "Pseudoinstruccion",
	"PROC":    "Pseudoinstruccion",
	"ENDP":    "Pseudoinstruccion",
	"ASSUME":  "Pseudoinstruccion",
	"EQU":     "Pseudoinstruccion",
	"ORG":     "Pseudoinstruccion",
	"END":     "Pseudoinstruccion",
}

var Registers16bits = map[string]string{
	"AX": "Registro de 16 bits",
	"BX": "Registro de 16 bits",
	"CX": "Registro de 16 bits",
	"DX": "Registro de 16 bits",
	"SP": "Registro de 16 bits",
	"BP": "Registro de 16 bits",
	"SI": "Registro de 16 bits",
	"DI": "Registro de 16 bits",
	"CS": "Registro de 16 bits",
	"DS": "Registro de 16 bits",
	"SS": "Registro de 16 bits",
	"ES": "Registro de 16 bits",
	"IP": "Registro de 16 bits",
}

var Registers8bits = map[string]string{
	"AL": "Registro de 1 byte",
	"AH": "Registro de 1 byte",
	"BL": "Registro de 1 byte",
	"BH": "Registro de 1 byte",
	"CL": "Registro de 1 byte",
	"CH": "Registro de 1 byte",
	"DL": "Registro de 1 byte",
	"DH": "Registro de 1 byte",
}

var Instructions = map[string]string{
	"DAA":   "Instruccion",
	"DAS":   "Instruccion",
	"PUSHF": "Instruccion",
	"RET":   "Instruccion",
	"CLC":   "Instruccion",
	"CLD":   "Instruccion",
	"PUSH":  "Instruccion",
	"NOT":   "Instruccion",
	"DIV":   "Instruccion",
	"POP":   "Instruccion",
	"CMP":   "Instruccion",
	"TEST":  "Instruccion",
	"LEA":   "Instruccion",
	"OR":    "Instruccion",
	"JNAE":  "Instruccion",
	"JNE":   "Instruccion",
	"JNLE":  "Instruccion",
	"LOOPE": "Instruccion",
	"JA":    "Instruccion",
	"JC":    "Instruccion",
}

var InvalidInstructions = map[string]string{
	"STC":    "Elemento invalido",
	"JNB":    "Elemento invalido",
	"HLT":    "Elemento invalido",
	"INTO":   "Elemento invalido",
	"JO":     "Elemento invalido",
	"LOOP":   "Elemento invalido",
	"JBE":    "Elemento invalido",
	"LODSB":  "Elemento invalido",
	"LODSW":  "Elemento invalido",
	"STOSB":  "Elemento invalido",
	"STOSW":  "Elemento invalido",
	"ADD":    "Elemento invalido",
	"LDS":    "Elemento invalido",
	"MOV":    "Elemento invalido",
	"LOOPNE": "Elemento invalido",
	"JG":     "Elemento invalido",
	"JMP":    "Elemento invalido",
	"JNBE":   "Elemento invalido",
	"CLI":    "Elemento invalido",
	"MOVSB":  "Elemento invalido",
	"MOVSW":  "Elemento invalido",
	"XLATB":  "Elemento invalido",
	"AAA":    "Elemento invalido",
	"ROR":    "Elemento invalido",
	"SUB":    "Elemento invalido",
	"JAE":    "Elemento invalido",
	"JL":     "Elemento invalido",
	"JNGE":   "Elemento invalido",
	"JNP":    "Elemento invalido",
	"JP":     "Elemento invalido",
	"CMC":    "Elemento invalido",
	"CMPSB":  "Elemento invalido",
	"NOP":    "Elemento invalido",
	"AAD":    "Elemento invalido",
	"AAM":    "Elemento invalido",
	"MUL":    "Elemento invalido",
	"INC":    "Elemento invalido",
	"INT":    "Elemento invalido",
	"AND":    "Elemento invalido",
	"XOR":    "Elemento invalido",
	"CWD":    "Elemento invalido",
	"PUSHA":  "Elemento invalido",
	"SAR":    "Elemento invalido",
	"ADC":    "Elemento invalido",
	"JNZ":    "Elemento invalido",
	"JZ":     "Elemento invalido",
	"JGE":    "Elemento invalido",
	"JNA":    "Elemento invalido",
	"JNC":    "Elemento invalido",
	"DEC":    "Elemento invalido",
	"IDIV":   "Elemento invalido",
	"LES":    "Elemento invalido",
	"RCL":    "Elemento invalido",
	"XCHG":   "Elemento invalido",
	"JB":     "Elemento invalido",
	"JE":     "Elemento invalido",
	"JLE":    "Elemento invalido",
	"JNL":    "Elemento invalido",
	"JNS":    "Elemento invalido",
	"JS":     "Elemento invalido",
	"CMPSW":  "Elemento invalido",
	"POPF":   "Elemento invalido",
	"LAHF":   "Elemento invalido",
	"POPA":   "Elemento invalido",
	"STD":    "Elemento invalido",
	"AAS":    "Elemento invalido",
	"STI":    "Elemento invalido",
	"CBW":    "Elemento invalido",
	"IMUL":   "Elemento invalido",
	"SCASW":  "Elemento invalido",
	"SHL":    "Elemento invalido",
	"JNG":    "Elemento invalido",
	"JNO":    "Elemento invalido",
	"JCXZ":   "Elemento invalido",
}
