package references

var PseudoInstructions = map[string]string{
	"DB":      "Pseudoinstruccion",
	"DW":      "Pseudoinstruccion",
	"DD":      "Pseudoinstruccion",
	"DQ":      "Pseudoinstruccion",
	"DT":      "Pseudoinstruccion",
	"SEGMENT": "Pseudoinstruccion",
	"ENDS":    "Pseudoinstruccion",
	"PROC":    "Pseudoinstruccion",
	"ENDP":    "Pseudoinstruccion",
	"ASSUME":  "Pseudoinstruccion",
	"EQU":     "Pseudoinstruccion",
	"ORG":     "Pseudoinstruccion",
	"END":     "Pseudoinstruccion",
}

var Registers16bits = map[string]string{
	"AX": "Registro de 16 bits",
	"BX": "Registro de 16 bits",
	"CX": "Registro de 16 bits",
	"DX": "Registro de 16 bits",
	"SP": "Registro de 16 bits",
	"BP": "Registro de 16 bits",
	"SI": "Registro de 16 bits",
	"DI": "Registro de 16 bits",
	"CS": "Registro de 16 bits",
	"DS": "Registro de 16 bits",
	"SS": "Registro de 16 bits",
	"ES": "Registro de 16 bits",
	"IP": "Registro de 16 bits",
}

var Registers8bits = map[string]string{
	"AL": "Registro de 1 byte",
	"AH": "Registro de 1 byte",
	"BL": "Registro de 1 byte",
	"BH": "Registro de 1 byte",
	"CL": "Registro de 1 byte",
	"CH": "Registro de 1 byte",
	"DL": "Registro de 1 byte",
	"DH": "Registro de 1 byte",
}

var Instructions = map[string]string{
	"MOV":  "Instrucción",
	"ADD":  "Instrucción",
	"SUB":  "Instrucción",
	"MUL":  "Instrucción",
	"DIV":  "Instrucción",
	"INC":  "Instrucción",
	"DEC":  "Instrucción",
	"AND":  "Instrucción",
	"OR":   "Instrucción",
	"XOR":  "Instrucción",
	"NOT":  "Instrucción",
	"SHL":  "Instrucción",
	"SHR":  "Instrucción",
	"JMP":  "Instrucción",
	"JE":   "Instrucción",
	"JNE":  "Instrucción",
	"JA":   "Instrucción",
	"JAE":  "Instrucción",
	"JB":   "Instrucción",
	"JBE":  "Instrucción",
	"CALL": "Instrucción",
	"RET":  "Instrucción",
	"PUSH": "Instrucción",
	"POP":  "Instrucción",
	"INT":  "Instrucción",
	"CMP":  "Instrucción",
	"TEST": "Instrucción",
	"LOOP": "Instrucción",
	"IN":   "Instrucción",
	"OUT":  "Instrucción",
	"LEA":  "Instrucción",
	"NOP":  "Instrucción",
	"HLT":  "Instrucción",
}
